<?php
/**
 * Created by BChar
 * Date: 04/07/2018
 * Time: 22:42
 * src/Service/FileUploader.php
 */
namespace App\Service;

// ================================================================================================================== //
// Imports.                                                                                                           //
// ================================================================================================================== //
use Symfony\Component\HttpFoundation\File\UploadedFile;


// ================================================================================================================== //
// Service.                                                                                                           //
// ================================================================================================================== //
class FileUploader{
    // Attributs.
    // ----------
    private $targetDirectory;

    // Constructeur.
    // -------------
    public function __construct($targetDirectory){
        $this->targetDirectory = $targetDirectory;
    }

    // Méthodes.
    // ---------
    // Créat° d'un nom unique + stockage dans le dossier paramétré.
    public function upload(UploadedFile $file){
        // md5() reduces the similarity of the file names generated by uniqid(), which is based on timestamps
        $fileName = md5(uniqid()).'.'.$file->guessExtension();

        $file->move($this->getTargetDirectory(), $fileName);

        return $fileName;
    }

    // Récupérat°, à la construction, du dossier de stockage (en parameters: uploads_directory).
    public function getTargetDirectory(){
        return $this->targetDirectory;
    }
}